# do not touch the config version below, it will break the plugin!
configversion: 1.1
duelme:
    checkforupdates: true
    duel:
       seperateinventories: true
       rightclicktoduel: false
    announce:
       duelstart: true
       deaths: true
       leavejoin: true
    commands:
       duelstart:
          - 'give %player% 298 1'
          - 'give %player% 299 1'
          - 'give %player% 300 1'
          - 'give %player% 301 1'
          - 'give %player% 268 1'
       duelwinner:
          - 'give %player% 267 1'

