# do not touch the config version below, it will break the plugin!
configversion: 1.1
duelme:
    checkforupdates: true
    duel:
       seperateinventories: true
       rightclicktoduel: false
    announce:
       duelstart: true
       deaths: true
    commands:
       duelstart:
          - 'example command'
          - 'example command 2'
       duelwinner:
          - 'winner command 1'
          - 'winner command 2'

