duelme:
    checkforupdates: true
    duelsenderloc:
        world:
        x:
        y:
        z:
    dueltargetloc:
        world:
        x:
        y:
        z:
    lobbyspawnloc:
        world:
        x:
        y:
        z:
    spectatespawnloc:
        world:
        x:
        y:
        z: