name: DuelMe
version: 0.2
author: teozfrank
main: com.teozcommunity.teozfrank.duelme.main.DuelMe
commands:
    duel:
        description: Access to duel commands
        permission: duelme.duel
        permission-message: You do not have permission for this command!
        usage: /<command>
    dueladmin:
        description: Access to dueladmin commands
        permission: duelme.admin
        permission-message: You do not have permission for this command!
        useage: /<command>