name: DuelMe
version: 0.1
author: teozfrank
main: com.teozcommunity.teozfrank.duelme.main.DuelMe
commands:
    duel:
        description: Access to duel commands
        permission: duelme.duel
        permission-message: You do not have permission for this command!
        usage: /<command>